package com.evelolvetech.service

import com.evelolvetech.data.requests.CreateCategoryRequest
import com.evelolvetech.data.requests.UpdateCategoryRequest
import com.evelolvetech.mocks.MockCategoryRepository
import kotlinx.coroutines.runBlocking
import com.evelolvetech.service.mom.ecommerce.CategoryService
import kotlin.test.*

class CategoryServiceTest {

    private val mockCategoryRepository = MockCategoryRepository()
    private val categoryService = CategoryService(mockCategoryRepository)

    @Test
    fun testCreateCategorySuccess() = runBlocking {
        val request = CreateCategoryRequest(
            name = "Test Category",
            slug = "test-category"
        )

        val result = categoryService.createCategory(request)

        assertNotNull(result)
        assertEquals("Test Category", result?.name)
        assertEquals("test-category", result?.slug)
    }

    @Test
    fun testCreateCategoryWithAutoGeneratedSlug() = runBlocking {
        val request = CreateCategoryRequest(
            name = "Baby Care & Health"
        )

        val result = categoryService.createCategory(request)

        assertNotNull(result)
        assertEquals("Baby Care & Health", result?.name)
        assertEquals("baby-care-health", result?.slug)
    }

    @Test
    fun testGetCategoryByIdSuccess() = runBlocking {
        val categoryId = "cat_fitness"

        val result = categoryService.getCategoryById(categoryId)

        assertNotNull(result)
        assertEquals("Fitness & Wellness", result?.name)
        assertEquals("fitness-wellness", result?.slug)
    }

    @Test
    fun testGetCategoryByIdNotFound() = runBlocking {
        val categoryId = "cat_nonexistent"

        val result = categoryService.getCategoryById(categoryId)

        assertNull(result)
    }

    @Test
    fun testGetAllCategories() = runBlocking {
        val result = categoryService.getAllCategories()

        assertNotNull(result)
        assertTrue(result.isNotEmpty())
        assertEquals(5, result.size)
    }

    @Test
    fun testUpdateCategorySuccess() = runBlocking {
        val categoryId = "cat_fitness"
        val request = UpdateCategoryRequest(
            name = "Updated Fitness",
            slug = "updated-fitness"
        )

        val result = categoryService.updateCategory(categoryId, request)

        assertTrue(result)
    }

    @Test
    fun testUpdateCategoryNotFound() = runBlocking {
        val categoryId = "cat_nonexistent"
        val request = UpdateCategoryRequest(
            name = "Updated Category",
            slug = "updated-category"
        )

        val result = categoryService.updateCategory(categoryId, request)

        assertFalse(result)
    }

    @Test
    fun testDeleteCategorySuccess() = runBlocking {
        val categoryId = "cat_fitness"

        val result = categoryService.deleteCategory(categoryId)

        assertTrue(result)
    }

    @Test
    fun testDeleteCategoryNotFound() = runBlocking {
        val categoryId = "cat_nonexistent"

        val result = categoryService.deleteCategory(categoryId)

        assertFalse(result)
    }
}
